### ISSUE TITLE
Integrate with 4EVERLAND pin service

### ISSUE THREAD

**Issue by saullary** [Uniswap/interface#4883]
**Introduce**
[4EVERLAND](https://www.4everland.org/) can provide you with free Pin service and global acceleration.

**Step**
1. Open [Dashboard](https://dashboard.4everland.org/) and connect with wallet
2. Create token in [Auth Tokens](https://dashboard.4everland.org/hosting/auth-tokens), and add it as EVER_TOKEN in Settings->Secrets->Actions
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/86224849/195286662-5e8f860d-8b12-4412-8165-39a2f90eb3f1.png">

3. Add script below to workflows
```
- name: Pin to 4everland
        uses: 4everland/pin-action@main
        continue-on-error: true
        timeout-minutes: 2
        with:
          EVER_TOKEN: ${{ secrets.EVER_TOKEN }}
          EVER_PROJECT_NAME: 'uniswap-interface'
          path: './build'
```
